-- Development seed data for Supabase.
-- Do NOT put real Personally Identifiable Information (PII) here.
-- This file is for local development only.
--
-- The site has no authentication, so there are no users to seed. `leads` is left
-- empty on purpose: the E2E suite writes its own fixture rows through the real
-- server path, which is also what verifies that path.
--
-- Example fixture (uncomment only for manual local inspection):
-- INSERT INTO public.leads
--   (full_name, business_name, phone, email, message, idempotency_key, request_id)
-- VALUES
--   ('בדיקה מקומית', 'עסק לדוגמה', '050-0000000', 'local@example.test',
--    'שורת בדיקה מקומית בלבד, ללא מידע אישי אמיתי.',
--    'seed-key-000000000001', 'seed-request');
