import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ImageResponse } from "next/og";
import {
  systemizeBrandColors,
  systemizeMarkSvg,
} from "@/components/brand/systemize-mark-geometry";
import { processStages } from "@/features/process/process-content";
import { openGraphImageAlt, openGraphImageSize } from "@/lib/seo/open-graph-image";
import { siteTagline } from "@/lib/site-config";

/**
 * The site's Open Graph image.
 *
 * Generated by the framework's own metadata-image route rather than shipped as a file:
 * AGENTS.md §9 names framework-generated metadata images as a valid exception to the
 * `next/image` rule, and generating it is what keeps the card honest, the words on it are
 * `siteTagline` and the four process stage titles, read from the same modules the page
 * renders. Nothing is written here, so the card cannot advertise a claim the site does not
 * make, and no stock photograph or invented logo appears on it.
 *
 * Heebo is loaded from the repository because the default font in the image runtime has no
 * Hebrew coverage, every glyph in the tagline would render as a blank box. The two static
 * instances live in `src/assets/fonts` with their OFL licence.
 *
 * The file convention applies this image to every route beneath `src/app`, so the home
 * page and the three legal routes all resolve an absolute `og:image` against
 * `metadataBase`, which reads `NEXT_PUBLIC_SITE_URL`. No host is written here.
 */
export const size = { ...openGraphImageSize };
export const contentType = "image/png";
export const alt = openGraphImageAlt;

const fontsDirectory = join(process.cwd(), "src", "assets", "fonts");

/**
 * The brand mark, inlined for the image runtime.
 *
 * Satori renders no React component tree beyond its own layout primitives, so the mark
 * cannot be imported from `@/components/brand/SystemizeMark`; it is carried here as a
 * data URI, which Satori does resolve. It is serialised from the same canonical geometry
 * as the component; `src/app/icon.svg` is generated from that source too.
 */
const markSource = `data:image/svg+xml;base64,${Buffer.from(
  systemizeMarkSvg({
    ink: systemizeBrandColors.ink,
  })
).toString("base64")}`;

/**
 * The tagline, broken into single-line boxes at its own comma.
 *
 * Satori, the layout engine behind `ImageResponse`, reorders bidirectional *text*
 * correctly but does not resolve `direction: rtl` when it aligns boxes: `text-align: start`
 * still resolves to the physical left, so a wrapped Hebrew line ends up ragged on the
 * reading edge, with the two lines' beginnings not aligned. Verified against the rendered
 * PNG, not assumed.
 *
 * Rather than reach for a physical `text-align: right`, forbidden by AGENTS.md §7, each
 * line is given its own box, so alignment becomes pure block placement and the
 * flow-relative `align-items: flex-end` on the container is enough.
 *
 * The comma is dropped rather than carried onto the end of the first line. The same engine
 * treats the base paragraph direction as left-to-right and therefore places a *trailing*
 * neutral character on the wrong edge, the comma rendered at the line's right edge, which
 * is the position a Hebrew reader reads first. A RIGHT-TO-LEFT MARK (U+200F) is the
 * textbook fix and does not work here either: the engine gives it a visible glyph instead
 * of treating it as a zero-width control. Both were verified against the rendered PNG.
 *
 * A line break standing in for a comma is ordinary typesetting, so the card still reads
 * exactly as the tagline does. Every word of `siteTagline` is preserved and in order, and
 * the full string including its comma is what `openGraphImageAlt` carries.
 */
function taglineLines(tagline: string): readonly string[] {
  const separator = ", ";
  const index = tagline.indexOf(separator);
  if (index === -1) return [tagline];
  return [tagline.slice(0, index), tagline.slice(index + separator.length)];
}

export default async function OpenGraphImage() {
  const [bold, medium] = await Promise.all([
    readFile(join(fontsDirectory, "Heebo-Bold.ttf")),
    readFile(join(fontsDirectory, "Heebo-Medium.ttf")),
  ]);

  const stages = processStages.map((stage) => stage.title).join("  ·  ");
  const lines = taglineLines(siteTagline);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          direction: "rtl",
          alignItems: "flex-end",
          padding: "72px 80px",
          backgroundColor: "#f1f2f3",
          backgroundImage:
            "radial-gradient(circle at 85% 12%, #d8f0f3 0%, rgba(216,240,243,0) 55%)",
          fontFamily: "Heebo",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
          {/* eslint-disable-next-line @next/next/no-img-element -- the image runtime
              has no `next/image`; this is the framework's own metadata image. */}
          <img src={markSource} width={44} height={44} alt="" />
          <div
            style={{
              fontSize: 34,
              fontWeight: 700,
              letterSpacing: 6,
              color: "#2b3440",
            }}
          >
            SYSTEMIZE
          </div>
        </div>

        <div
          style={{ display: "flex", flexDirection: "column", alignItems: "flex-end" }}
        >
          <div
            style={{
              display: "flex",
              width: 96,
              height: 6,
              borderRadius: 3,
              backgroundColor: "#4bb8c4",
              marginBottom: 32,
            }}
          />
          {lines.map((line) => (
            <div
              key={line}
              style={{
                fontSize: 72,
                fontWeight: 700,
                lineHeight: 1.24,
                letterSpacing: -2,
                color: "#20262f",
              }}
            >
              {line}
            </div>
          ))}
        </div>

        <div
          style={{
            display: "flex",
            fontSize: 34,
            fontWeight: 500,
            letterSpacing: 2,
            color: "#5a6472",
          }}
        >
          {stages}
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        { name: "Heebo", data: bold, weight: 700, style: "normal" },
        { name: "Heebo", data: medium, weight: 500, style: "normal" },
      ],
    }
  );
}
